#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets

runApplication blockMesh
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar
postProcess -func vorticity


